[mgr]
cwd = { fg = "#61AFEF" }

find_keyword = { fg = "#E06C75", italic = true, underline = true }
find_position = { fg = "#E5C07B", italic = true }

marker_copied = { fg = "#ABB2BF", bg = "#98C379" }
marker_cut = { fg = "#ABB2BF", bg = "#E06C75" }
marker_marked = { fg = "#ABB2BF", bg = "#56B6C2" }
marker_selected = { fg = "#ABB2BF", bg = "#E5C07B" }

count_copied = { fg = "#98C379", bg = "#282C34" }
count_cut = { fg = "#E06C75", bg = "#282C34" }
count_selected = { fg = "#98C379", bg = "#282C34" }

border_symbol = "│"
border_style = { fg = "#282C34" }

[tabs]
active = { bg = "#282C34", fg = "#61AFEF" }
inactive = {}
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#282C34", bg = "#61AFEF", bold = true }
normal_alt = { fg = "#61AFEF", bg = "#282C34" }

select_main = { fg = "#282C34", bg = "#98C379", bold = true }
select_alt = { fg = "#98C379", bg = "#282C34" }

unset_main = { fg = "#282C34", bg = "#E5C07B", bold = true }
unset_alt = { fg = "#E5C07B", bg = "#282C34" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#ABB2BF", bold = true }
progress_normal = { fg = "#98C379", bg = "#282C34" }
progress_error = { fg = "#E06C75", bg = "#282C34" }

perm_type = { fg = "#98C379" }
perm_read = { fg = "#E06C75" }
perm_write = { fg = "#E5C07B" }
perm_exec = { fg = "#98C379" }

[pick]
border = { fg = "#98C379" }
active = { fg = "#E5C07B", bold = true }
inactive = {}

[input]
border = { fg = "#98C379" }
title = {}
value = {}
selected = { reversed = true }

[cmp]
border = { fg = "#98C379" }

[tasks]
border = { fg = "#98C379" }
title = {}
hovered = { fg = "#E5C07B", underline = true }

[which]
mask = { bg = "#282C34" }
cand = { fg = "#98C379" }
rest = { fg = "#ABB2BF" }
desc = { fg = "#E5C07B" }
separator = "  "
separator_style = { fg = "#ABB2BF" }

[help]
on = { fg = "#98C379" }
run = { fg = "#E5C07B" }
hovered = { reversed = true, bold = true }
footer = { fg = "#ABB2BF", bg = "#000000" }

[notify]
title_info = { fg = "#98C379" }
title_warn = { fg = "#E06C75" }
title_error = { fg = "#E5C07B" }

[filetype]
rules = [
    { mime = "image/*", fg = "#E5C07B" },

    { mime = "video/*", fg = "#E06C75" },
    { mime = "audio/*", fg = "#E06C75" },

    { mime = "application/{zip,tar,bzip*,7z-compressed,xz,rar}", fg = "#C678DD" },

    { mime = "application/{pdf,rtf}", fg = "#98C379" },
    { mime = "application/vnd.*", fg = "#98C379" },
]
